### ISSUE TITLE
Task 16: Display "Create Teams" Button on Instructor Dashboard (UI)

### ISSUE THREAD

**Issue by KevinMandiouba** [SOEN341Fall2024/IterationX-SOEN341_Project_F24#43]
**Task Description:**
Ensure the "Create Teams" button is visible on the Instructor Dashboard. The button should be styled according to the overall theme of the application.

_This task is part of US.02: Instructor: Create Teams and Assign Students._

**Comment by Joyal99** [comment]
Task Complete
