### ISSUE TITLE
Task 20: Display "View Teams" Button on Instructor Dashboard (UI)

### ISSUE THREAD

**Issue by KevinMandiouba** [SOEN341Fall2024/IterationX-SOEN341_Project_F24#47]
**Task Description:**
Ensure the "View Teams" button is visible on the Instructor Dashboard and styled according to the overall theme of the application.

This task is part of [US.03: Instructor: View Assigned Teams](https://github.com/SOEN341Fall2024/IterationX-SOEN341_Project_F24/issues/33).

**Comment by Joyal99** [comment]
Task Completed
