### ISSUE TITLE
Task.21: Show List of Teams with Names and Members (UI)

### ISSUE THREAD

**Issue by KevinMandiouba** [SOEN341Fall2024/IterationX-SOEN341_Project_F24#48]
**Task Description:**
When the instructor clicks on the "View Teams" button, display a list of teams along with their respective names and members in a well-organized table or list.

This task is part of [US.03: Instructor: View Assigned Teams](https://github.com/SOEN341Fall2024/IterationX-SOEN341_Project_F24/issues/33).

**Comment by Joyal99** [comment]
Completed
