### ISSUE TITLE
Task.22: Allow Instructor to Select a Team to View Detailed Information (UI)

### ISSUE THREAD

**Issue by KevinMandiouba** [SOEN341Fall2024/IterationX-SOEN341_Project_F24#49]
**Task Description:**
Implement functionality for the instructor to select a team from the displayed list to view detailed information, including team members and other relevant data.

This task is part of [US.03: Instructor: View Assigned Teams](https://github.com/SOEN341Fall2024/IterationX-SOEN341_Project_F24/issues/33).

**Comment by Joyal99** [comment]
Completed
