### ISSUE TITLE
Task.23: Display Detailed Team Information (UI)

### ISSUE THREAD

**Issue by KevinMandiouba** [SOEN341Fall2024/IterationX-SOEN341_Project_F24#50]
**Task Description:**
Style the detailed team information view, ensuring that all team-related details (members, tasks, etc.) are displayed clearly and intuitively for the user.

This task is part of [US.03: Instructor: View Assigned Teams](https://github.com/SOEN341Fall2024/IterationX-SOEN341_Project_F24/issues/33).

**Comment by Joyal99** [comment]
Completed
