### ISSUE TITLE
Task.24: Navigation Back to Dashboard or Other Management Options (UI)

### ISSUE THREAD

**Issue by KevinMandiouba** [SOEN341Fall2024/IterationX-SOEN341_Project_F24#51]
**Task Description:**
Provide a button or link allowing the instructor to navigate back to the dashboard or other management options from the detailed team view.

This task is part of [US.03: Instructor: View Assigned Teams](https://github.com/SOEN341Fall2024/IterationX-SOEN341_Project_F24/issues/33).

**Comment by Joyal99** [comment]
Completed
