### ISSUE TITLE
Task.25: Display "View Teams" Button on Student Dashboard (UI)

### ISSUE THREAD

**Issue by KevinMandiouba** [SOEN341Fall2024/IterationX-SOEN341_Project_F24#53]
**Task Description:**
Ensure the "View Teams" button is visible on the Student Dashboard and styled according to the application's theme.

This task is part of [US.04: Student: View Assigned Teams](https://github.com/SOEN341Fall2024/IterationX-SOEN341_Project_F24/issues/42).

**Comment by Joyal99** [comment]
Completed
