### ISSUE TITLE
Task.29: Display "Edit Teams" Button on Instructor Dashboard (UI)

### ISSUE THREAD

**Issue by KevinMandiouba** [SOEN341Fall2024/IterationX-SOEN341_Project_F24#57]
**Task Description:**
Ensure the "Edit Teams" button is visible on the Instructor Dashboard and styled according to the application's theme.

This task is part of [US.05: Instructor: Edit Teams](https://github.com/SOEN341Fall2024/IterationX-SOEN341_Project_F24/issues/41).

**Comment by Joyal99** [comment]
Completed
