### ISSUE TITLE
US.07 - Instructor and Student: View Notifications

### ISSUE THREAD

**Issue by Joyal99** [SOEN341Fall2024/IterationX-SOEN341_Project_F24#74]
**User Story Description**

As both an instructor and a student, I want to access a notification button that provides options when clicked so that I can quickly manage or view important updates.

**User Acceptance Flow**

1. The user (instructor or student) is logged in and navigates to their respective dashboard.
2. The user clicks the "Notification" button on the dashboard.
3. A dropdown menu with three options is displayed: "View All Notifications," "Mark All as Read," and "Notification Settings."
4. The user can select any of the options to perform the respective action.

**Acceptance Criteria**

Task.40: Implement the "Notification" button for both instructor and student dashboards (UI) #70
Task.41: Display a dropdown with three options ("View All Notifications," "Mark All as Read," and "Notification Settings") when clicking the notification button (UI) #71

**Comment by ouss2231** [comment]
it has already been done.
